### ISSUE TITLE
getting 404s when hitting evented and mvc there is no package.json in footer directory

### ISSUE THREAD

**Issue by minmaxdata** [jherr/web-components-pdp#12]
I have cloned your repo and ran the install shell script - when i run the build script 
--------------------------------
sh ./build.sh
yarn run v1.22.5
$ node scripts/build.js
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Compiled successfully.

File sizes after gzip:

  40.33 KB  build/static/js/main.js

The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  https://bit.ly/CRA-deploy

✨  Done in 7.76s.
yarn run v1.22.5
error Couldn't find a package.json file in "/Users/???/code/jherr/web-components-pdp/components/footer"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.5
$ node scripts/build.js
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Compiled successfully.

File sizes after gzip:

  40.26 KB  build/static/js/main.js

The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  https://bit.ly/CRA-deploy

✨  Done in 7.45s.
yarn run v1.22.5
$ vue-cli-service build --target wc --name my-header ./src/main.js

⠼  Building for production as web component...Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
⠋  Building for production as web component...Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
⠼  Building for production as web component...

 WARNING  Compiled with 1 warnings                                                                                1:15:35 PM

 warning  in ./node_modules/@vue/cli-service/lib/commands/build/entry-wc.js

"export 'default' (imported as 'myHeader') was not found in '~root/./src/main.js?shadow'

⠇  Building for production as web component...

 WARNING  Compiled with 1 warnings                                                                                1:15:35 PM

 warning  in ./node_modules/@vue/cli-service/lib/commands/build/entry-wc.js

"export 'default' (imported as 'myHeader') was not found in '~root/./src/main.js?shadow'

  File                     Size                     Gzipped

  dist/my-header.min.js    8.01 KiB                 3.49 KiB
  dist/my-header.js        27.01 KiB                7.71 KiB

  Images and other types of assets omitted.

✨  Done in 8.65s.
-----------------

**run the site**
python -m SimpleHTTPServer 8000

**when i go to** 
#Then navigate to http://localhost:8000/evented/ or http://localhost:8000/mvc/

I get 404s

﻿
when i got to http://localhost:8000/host-simple/ the following is logged to my console

localhost/:33 GET http://localhost:8000/components/footer/dist/my-footer.min.js net::ERR_ABORTED 404 (File not found)
vue-wc-wrapper.js:113 Uncaught TypeError: Cannot read property 'props' of undefined
    at c (vue-wc-wrapper.js:113)
    at g (vue-wc-wrapper.js:261)
    at Module.5a74 (entry-wc.js:11)
    at n (bootstrap:19)
    at bootstrap:83
    at my-header.min.js:1
vue:9055 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vue:9064 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
localhost/:33 GET http://localhost:8000/components/footer/dist/my-footer.min.js net::ERR_ABORTED 404 (File not found)
﻿
​

**Comment by jherr** [comment]
Ok. Might take me a bit to get around to this. It's been a while since I worked on this repo.

**Comment by jherr** [comment]
We should be good now. Somehow footer got set up as a git submodule? So weird.
